### PR TITLE
doc update:Sun Apr 23 06:26:46 UTC 2017

### PR DESCRIPTION
**Pull request by TheBBot**
My life for Spacemacs!

### CODE REVIEW

**Comment by JAremko** [comment]
Dat boi @TheBBot 

Now I need to add a CI link 404 test on develop.spacemacs.org PRs and we are done

 - - - - - -

Btw this PR is based on the Spacemacs develop branch (just for testing) **<DON'T MERGE>**

- - - - - -

` from unknown repository` <- because  I deleted the original fork. It will be `from TheBBot:gh-pages`

**Comment by syl20bnr** [comment]
Nice :-D
The name of the bot made me laugh but I would like a more neutral bot name in relation with the project instead of a maintainer based name ;-)

**Comment by syl20bnr** [comment]
BTW, this should not be merged at all ? I mean this is the develop version of the website which is meant to be up to date with the develop branch of Spacemacs.

**Comment by JAremko** [comment]
> BTW, this should not be merged at all ? I mean this is the develop version of the website which is meant to be up to date with the develop branch of Spacemacs.

Hm. I was thinking that develop.spacemacs.org is a testing ground for spacemacs.org 

- - - -

Do we really need a separate develop site?  I think it will be better to have documentation for the both branches on the same site. 

 - - - -

>The name of the bot made me laugh but I would like a more neutral bot name in relation with the project instead of a maintainer based name ;-)

Well... I have already made https://github.com/robocobra so I decided to give him a company

**Pull request closed without merging**
