### PR TITLE
Documentation updates (autoexport)

### PR DESCRIPTION
**Pull request by emacspace**
beep beep boop... Beep?

### CODE REVIEW

**Comment by saper** [comment]
I am a beginner here, how do I export org pages into HTML? I noticed some links like http://spacemacs.org/doc/DOCUMENTATION.org#special-buffers in http://spacemacs.org/doc/VIMUSERS.html#special-buffers give 404 because they point to the org files.

I also wanted to change all the instances of "here" links.

**Comment by JAremko** [comment]
@saper We have already fixed all 404 errors in Spacemacs develop branch  http://develop.spacemacs.org/doc/VIMUSERS.html#special-buffers  We just haven't master release (with the fixes) for a long time.

**Comment by saper** [comment]
@JAremko thank you! this is nice, I hope it gets deployed on the main site quickly. How do I rebuild documentation myself to test my changes?

**Comment by JAremko** [comment]
@saper 

``` sh
    echo_headline "INSTALLING DEPENDENCIES:"
    cp ~/.emacs.d/.travisci/.spacemacs ~/
    cd  ~/.emacs.d
    emacs -batch -l init.el

    echo_headline "EXPORTING DOCUMENTATION:"
    emacs -batch -l init.el -l core/core-documentation.el \
          -f spacemacs/publish-doc
    if [ $? -ne 0 ]; then
        echo "spacemacs/publish-doc failed"
        exit 2
    fi
```

Or you can load `core/core-documentation.el` and call `spacemacs/publish-doc` from Spacemacs.  If you get an error then first open random .org file and call it again(it will load missing deps)

Then look into `~/.emacs.d/export/` folder.

  See [Travis script](https://github.com/syl20bnr/spacemacs/blob/develop/.travisci/pub.sh#L89)

**Comment by JAremko** [comment]
Also you can auto-check for 404 https://github.com/syl20bnr/develop.spacemacs.org/blob/gh-pages/travis/travis.sh

**Comment by saper** [comment]
Thanks! I was looking at circle ci files and got lost a bit.

**Pull request merged**
